site_name: b-package
site_url: https://brunofariadf.github.io/b-package"
# repo_url: "https://github.com/brunofariadf/b-package"
theme: 
  name: windmill
  favicon: img/favicon.png
# copyright: test

plugins:
  - mkdocs-jupyter:
      execute: True
  - search

nav:
  # - Home: index.md
  - introduction: introduction.md
  - vscoder: vscoder/vscoder.ipynb
  - changelog: changelog.md

markdown_extensions:
  - attr_list
  - toc:
      permalink: '#'

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      # custom_fences:
      #   - name: mermaid
      #     class: mermaid
      #     format: !!python/name:pymdownx.superfences.fence_div_format

extra:
  history_buttons: false
  version: 0.2.1.9000
extra_css: [stylesheets/style.css]
